In [16]:
import pandas as pd

In [17]:
data_p1='/mnt/GSHD_DATA_01/partner/icool/revenue/output/1/2022.02.18/predict_316.csv'

In [18]:
data_01=pd.read_csv(data_p1)

In [19]:
data_01.head()

         ngay    doanhthu
0  2022-02-18  111.251295
1  2022-02-19  147.571749
2  2022-02-20   89.856156
3  2022-02-21   58.331009
4  2022-02-22   68.763153

In [20]:
data_p2='/mnt/GSHD_DATA_01/partner/icool/revenue/data/DT_20220101_20220217.csv'
dt_2021=pd.read_csv(data_p2, sep='\t')

In [21]:
dt_2021.head(3)

,name,id,date,cuahang_id,sum,total,mon,customer,bill,vat,...,hours,tour,expense,room,profit,created_by,created_date,modified_by,modified_date,trangthai
0,ICOOL V?ng T�u,47EDE6D1-246B-EC11-810F-509A4C8C9FAC,01/01/2022,25,42314700.0,42035700.0,0.0,0.0,279000.0,0.0,...,40,2.35,0,17,29488415.57,system,04:04.1,system,NaN,4
1,ICOOL Ung V?n Khi�m,7EC958F6-ED6B-EC11-810F-509A4C8C9FAC,02/01/2022,1,33377000.0,33377000.0,0.0,0.0,0.0,0.0,...,30,0.00,0,37,15707932.87,system,03:53.7,system,NaN,4
2,ICOOL V?ng T�u,2A9C9DFC-ED6B-EC11-810F-509A4C8C9FAC,02/01/2022,25,20040100.0,19826085.0,0.0,0.0,214015.0,0.0,...,40,1.18,0,17,12476631.02,system,04:04.1,system,NaN,4

In [22]:
dt_2021=dt_2021[['date', 'cuahang_id', 'total']]
dt_2021.columns=['ngay', 'macuahang', 'doanhthu']

In [23]:
dt_2021.head()

         ngay  macuahang    doanhthu
0  01/01/2022         25  42035700.0
1  02/01/2022          1  33377000.0
2  02/01/2022         25  19826085.0
3  03/01/2022          1  13631000.0
4  03/01/2022         25   3040600.0

In [24]:
dt_2021['doanhthu']=round(dt_2021['doanhthu']/1000000,2)

In [25]:
dt_2021.head()

         ngay  macuahang  doanhthu
0  01/01/2022         25     42.04
1  02/01/2022          1     33.38
2  02/01/2022         25     19.83
3  03/01/2022          1     13.63
4  03/01/2022         25      3.04

In [26]:
list_CH=list(set(dt_2021['macuahang'].tolist()))
list_CH=list_CH[:-2]

In [27]:
list_CH

[1, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 22, 23]

In [28]:
for x in list_CH:
    ## read predict from 2022/02/18-2022/12/31
    data_p1=f'/mnt/GSHD_DATA_01/partner/icool/revenue/output/{x}/2022.02.18/predict_316.csv'
    data_01=pd.read_csv(data_p1)

    ## read gt from 2022/01/01-2022/02/17
    data_02=dt_2021[dt_2021['macuahang']==x]
    total=data_01['doanhthu'].tolist()+data_02['doanhthu'].tolist()
    total=round(sum(total)/1000, 4)

    print(f'==> doanh thu du bao cua cua hang: {x} la: {total} ty VND')

==> doanh thu du bao cua cua hang: 1 la: 38.1954 ty VND
==> doanh thu du bao cua cua hang: 4 la: 20.2823 ty VND
==> doanh thu du bao cua cua hang: 5 la: 16.1788 ty VND
==> doanh thu du bao cua cua hang: 6 la: 22.3075 ty VND
==> doanh thu du bao cua cua hang: 7 la: 40.047 ty VND
==> doanh thu du bao cua cua hang: 9 la: 13.6223 ty VND
==> doanh thu du bao cua cua hang: 10 la: 29.8704 ty VND
==> doanh thu du bao cua cua hang: 11 la: 8.5372 ty VND
==> doanh thu du bao cua cua hang: 12 la: 28.5851 ty VND
==> doanh thu du bao cua cua hang: 13 la: 12.1374 ty VND
==> doanh thu du bao cua cua hang: 14 la: 36.4467 ty VND
==> doanh thu du bao cua cua hang: 16 la: 8.0375 ty VND
==> doanh thu du bao cua cua hang: 17 la: 15.4914 ty VND
==> doanh thu du bao cua cua hang: 18 la: 30.8935 ty VND
==> doanh thu du bao cua cua hang: 19 la: 8.1875 ty VND
==> doanh thu du bao cua cua hang: 22 la: 20.559 ty VND
==> doanh thu du bao cua cua hang: 23 la: 10.3437 ty VND

In [29]:
total

10.3437